from api.endpoints.admins import AdminsEndpoint
from api.endpoints.auth_handler import AuthHandlerEndpoint
from api.endpoints.embedder import EmbedderEndpoint
from api.endpoints.file_manager import FileManagerEndpoint
from api.endpoints.large_language_model import LargeLanguageModelEndpoint
from api.endpoints.memory import MemoryEndpoint
from api.endpoints.message import MessageEndpoint
from api.endpoints.plugins import PluginsEndpoint
from api.endpoints.rabbit_hole import RabbitHoleEndpoint
from api.endpoints.settings import SettingsEndpoint
from api.endpoints.users import UsersEndpoint
